# Change these first
owner: FindyFi # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Findy.fi
    url: https://www.findy.fi
    icon: https://pensiondemo.findy.fi/favicon.ico
  - name: Findy Keycloak
    url: https://id.keycloak.findy.fi
    icon: https://www.keycloak.org/resources/favicon.ico
  - name: Walt.id Pilot Wallet
    url: https://waltid.pilot.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Pilot Issuer API
    url: https://issuer.waltid.pilot.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Pilot Verifier API
    url: https://verifier.waltid.pilot.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Pilot Wallet API
    url: https://wallet.waltid.pilot.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Test Wallet
    url: https://waltid.test.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Test Issuer API
    url: https://issuer.waltid.test.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Test Verifier API
    url: https://verifier.waltid.test.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Test Wallet API
    url: https://wallet.waltid.test.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Test Wallet Portal
    url: https://portal.waltid.test.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Dev Wallet
    url: https://waltid.dev.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Dev Issuer API
    url: https://issuer.waltid.dev.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Dev Verifier API
    url: https://verifier.waltid.dev.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Dev Wallet API
    url: https://wallet.waltid.dev.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Dev Wallet Portal
    url: https://portal.waltid.dev.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Friend of Findy
    url: https://friend.findy.fi/
    icon: https://friend.findy.fi/favicon.png
  - name: Opintopolku
    url: https://opintopolku.findy.fi
    icon: https://opintopolku.findy.fi/favicon.png
  - name: Pensiondemo
    url: https://pensiondemo.findy.fi
    icon: https://pensiondemo.findy.fi/favicon.ico
  - name: "Pensiondemo Gataca issuer"
    url: https://issuer.gataca.pensiondemo.findy.fi
    icon: https://gataca.io/favicon-32x32.png?v=857b836439065cf2b1e76cc41fb197fe
  - name: "Pensiondemo Gataca verifier"
    url: https://verifier.gataca.pensiondemo.findy.fi
    icon: https://gataca.io/favicon-32x32.png?v=857b836439065cf2b1e76cc41fb197fe
  - name: "Pensiondemo SICPA issuer"
    url: https://issuer.sicpa.pensiondemo.findy.fi
    icon: https://www.sicpa.com/themes/custom/sicpa_theme/sicpa.ico
  - name: "Pensiondemo SICPA verifier"
    url: https://verifier.sicpa.pensiondemo.findy.fi
    icon: https://www.sicpa.com/themes/custom/sicpa_theme/sicpa.ico
  - name: "Pensiondemo walt.id issuer"
    url: https://issuer.waltid.pensiondemo.findy.fi
    icon: https://walt.id/favicon.ico
  - name: "Pensiondemo walt.id verifier"
    url: https://verifier.waltid.pensiondemo.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Findy Web Wallet (CHAPI)
    url: https://webwallet.findy.fi/
    icon: https://webwallet.findy.fi/findy.png
  - name: Findy Job application demo (CHAPI)
    url: https://apply.test.findy.fi/
    icon: https://apply.test.findy.fi/favicon.png

skipDeleteIssues: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /
  cname: status.findy.fi
  favicon: https://findynet.fi/wp-content/uploads/2024/02/findynet-favicon-300x300.png
  logoUrl: https://findynet.fi/wp-content/uploads/2024/02/findynet-favicon-300x300.png
  name: Findynet Upptime
  introTitle: "Findynet Website monitoring."
  introMessage: "Status and status history of Findynet's web site, services, and demo sites."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Findy.fi
      href: https://findy.fi/
  themeUrl: https://status.findy.fi/findy.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
