# Change these first
owner: FindyFi # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Findynet.fi
    url: https://www.findynet.fi
    icon: http://findynet.fi/logo
  - name: Trust Registry Browser
    url: https://browser.trustregistry.eu/?entity=https%3A%2F%2Ffindy.trustregistry.eu
    icon: http://findynet.fi/logo    
#  - name: Findy Keycloak
#    url: https://id.keycloak.findy.fi
#    icon: https://www.keycloak.org/resources/favicon.ico
# Archived for the time being
#  - name: Friend of Findy
#    url: https://friend.findy.fi/
#    icon: https://friend.findy.fi/favicon.png
  - name: Hymy-todiste
    url: https://hymytodiste.fi/
    icon: https://hymytodiste.fi/hymy-green.svg
  - name: Kiltteystodiste
    url: https://joulu.todiste.fi/
    icon: https://joulu.todiste.fi/favicon.png
  - name: International Patient Summary
    url: https://ips.digicredential.eu/
    icon: https://ips.digicredential.eu/favicon.png
  - name: Opintopolku
    url: https://opintopolku.findy.fi
    icon: https://opintopolku.findy.fi/favicon.png
  - name: Pensiondemo
    url: https://pensiondemo.findy.fi
    icon: https://pensiondemo.findy.fi/favicon.ico
  - name: "Pensiondemo Authbound"
    url: https://authbound.pensiondemo.findy.fi
    icon: https://www.authbound.io/favicon.ico
#  - name: "Pensiondemo Gataca issuer"
#    url: https://issuer.gataca.pensiondemo.findy.fi
#    icon: https://gataca.io/favicon-32x32.png?v=857b836439065cf2b1e76cc41fb197fe
#  - name: "Pensiondemo Gataca verifier"
#    url: https://verifier.gataca.pensiondemo.findy.fi
#    icon: https://gataca.io/favicon-32x32.png?v=857b836439065cf2b1e76cc41fb197fe
  - name: "Pensiondemo Hovi issuer"
    url: https://issuer.hovi.pensiondemo.findy.fi
    icon: https://cdn.prod.website-files.com/659dad70ef0ae858f66ae208/65dc73e6b6a536fcaf9e45bd_favicon%20(1).jpg
  - name: "Pensiondemo Hovi verifier"
    url: https://verifier.hovi.pensiondemo.findy.fi
    icon: https://cdn.prod.website-files.com/659dad70ef0ae858f66ae208/65dc73e6b6a536fcaf9e45bd_favicon%20(1).jpg
  - name: "Pensiondemo Paradym issuer"
    url: https://issuer.paradym.pensiondemo.findy.fi
    icon: https://docs.paradym.id/images/fav.png
  - name: "Pensiondemo Paradym verifier"
    url: https://verifier.paradym.pensiondemo.findy.fi
    icon: https://docs.paradym.id/images/fav.png
  - name: "Pensiondemo Procivis issuer"
    url: https://issuer.procivis.pensiondemo.findy.fi
    icon: https://docs.procivis.ch/img/favicon.svg
  - name: "Pensiondemo Procivis verifier"
    url: https://verifier.procivis.pensiondemo.findy.fi
    icon: https://docs.procivis.ch/img/favicon.svg
#  - name: "Pensiondemo SICPA issuer"
#    url: https://issuer.sicpa.pensiondemo.findy.fi
#    icon: https://www.sicpa.com/themes/custom/sicpa_theme/sicpa.ico
#  - name: "Pensiondemo SICPA verifier"
#    url: https://verifier.sicpa.pensiondemo.findy.fi
#    icon: https://www.sicpa.com/themes/custom/sicpa_theme/sicpa.ico
  - name: "Pensiondemo Sphereon issuer"
    url: https://issuer.sphereon.pensiondemo.findy.fi
    icon: https://sphereon.com/content/themes/sphereon/assets/favicons/favicon-32x32.png
  - name: "Pensiondemo Sphereon verifier"
    url: https://verifier.sphereon.pensiondemo.findy.fi
    icon: https://sphereon.com/content/themes/sphereon/assets/favicons/favicon-32x32.png
  - name: "Pensiondemo walt.id issuer"
    url: https://issuer.waltid.pensiondemo.findy.fi
    icon: https://walt.id/favicon.ico
  - name: "Pensiondemo walt.id verifier"
    url: https://verifier.waltid.pensiondemo.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Findy Web Wallet (CHAPI)
    url: https://webwallet.findy.fi/
    icon: https://webwallet.findy.fi/findy.png
  - name: Findy Job application demo (CHAPI)
    url: https://apply.test.findy.fi/
    icon: https://apply.test.findy.fi/favicon.png
  - name: Walt.id Staging Wallet
    url: https://waltid.staging.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Staging Issuer API
    url: https://issuer.waltid.staging.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Staging Verifier API
    url: https://verifier.waltid.staging.findy.fi
    icon: https://walt.id/favicon.ico
  - name: Walt.id Staging Wallet API
    url: https://wallet.waltid.staging.findy.fi
    icon: https://walt.id/favicon.ico

skipDeleteIssues: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /
  cname: status.findy.fi
  favicon: https://findynet.fi/wp-content/uploads/2024/02/findynet-favicon-300x300.png
  logoUrl: https://findynet.fi/wp-content/uploads/2024/02/findynet-favicon-300x300.png
  name: Findynet Upptime
  introTitle: "Findynet Website monitoring."
  introMessage: "Status and status history of Findynet's web site, services, and demo sites."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Findynet.fi
      href: https://findynet.fi/
  themeUrl: https://status.findy.fi/findy.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
